---
title: "20240325"
author: "YinCY"
format: html
---

```{r}
#| message: false
#| warning: false
library(igraph)
library(tidygraph)
library(ggraph)

df <- read.table("/mnt/c/Users/yincy/Downloads/string_interactions.tsv", 
                 sep = "\t", 
                 header = TRUE)
df <- df %>% dplyr::select(node1, node2, combined_score)
df
```

```{r}
g <- graph_from_data_frame(d = df) %>% as_tbl_graph()
```

```{r}
set.seed(01)
ly <- igraph::layout.sphere(g)
coords <- cbind(g %>% activate(nodes) %>% as.data.frame, ly)
median <- ly %>% apply(2, median)
coords[coords$name == "Itih5", 2:3] <- median
ly <- coords[, 2:4] %>% as.matrix()

g %>% 
    ggraph(layout = ly) +
    geom_node_point(aes(filter = .N()$name != "Itih5", color = .N()$name), size = 4) +
    geom_node_point(aes(filter = .N()$name == "Itih5"), color = "blue", size = 4) +
    geom_edge_link(edge_width = 0.05, edge_alpha = 0.2, aes(color = .E()$combined_score)) +
    geom_node_text(aes(label = name, filter = .N()$name != "Itih5"), color = "black", size = 3) +
    geom_node_text(aes(label = name, filter = .N()$name == "Itih5"), color = "tomato", size = 3) +
    theme_graph() +
    theme(legend.position = "none") 

ggsave("network.pdf")
```

```{r}
grep("layout", ls("package:tidygraph"), value = TRUE)
```


















