---
title: "train classifer models"
author: YinCY
date: 2024-01-14
format: html
editor: source
---

# train a classifier model for bone marrow cells
```{r}
#| message: false
#| warning: false

library(scAnnotatR)
library(SingleCellExperiment)
library(magrittr)
library(EnsDb.Mmusculus.v79)
library(janitor)
```

```{r}
sces <- readRDS("../../../data/parttime/nasa/reference/processed_GSE122465.rds")
sces$cell_types <- as.character(sces$cell_types)
sces$cell_types <- make_clean_names(sces$cell_types, allow_dupes = TRUE)
cell_types <- sces$cell_types %>% unique()
names(cell_types) <- cell_types
sces %>% colData

load("../../../data/parttime/nasa/reference/NicheMarkers10x.rda")
NicheMarkers10x <- NicheMarkers10x %>% tibble::rownames_to_column("symbol") %>% 
    dplyr::mutate(symbol = gsub("\\.[0-9]{1,}$", "", symbol), 
                  ensembl = mapIds(EnsDb.Mmusculus.v79, keys = symbol, keytype = "SYMBOL", column = "GENEID")) %>% 
    dplyr::filter(!is.na(ensembl))

marker_list <- split(NicheMarkers10x$ensembl, 
                     make_clean_names(NicheMarkers10x$cluster, allow_dupes = TRUE))
marker_list %>% names
marker_list %>% sapply(length)
```

```{r}
for(cell_type in cell_types){
    # turn all non current cell to other cell
    cur_sces <- sces
    cur_sces$cell_types <- ifelse(cur_sces$cell_types == cell_type, cell_type, "others")
    
    cur_model <- train_classifier(train_obj = cur_sces, 
                                  assay = "logcounts", 
                                  cell_type = cell_type, 
                                  marker_genes = marker_list[[cell_type]], 
                                  tag_slot = cell_types[cell_type])
    
    # # save the current model
    # save_new_model(new_model = cur_model, 
    #                include.default = FALSE, 
    #                path_to_models = "../../../data/scAnnotatR/bone_marrow_models/")
}
```

```{r}
cur_sces$cell_types %>% unique
cur_model <- train_classifier(train_obj = cur_sces, 
                              assay = "logcounts",
                              cell_type = "ery_mk_prog", 
                              marker_genes = marker_list[["ery_mk_prog"]], 
                              tag_slot = "ery_mk_prog")
```












