---
title: "kidney macrophage"
author: "YinCY"
date: "11/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(fgsea)
library(msigdbr)
library(tidyverse)
library(GO.db)
library(org.Mm.eg.db)
```

```{r}
kidney_macrophage <- readxl::read_xlsx("../../sslab/kidney/data/20200530_DE_FDR_2.xlsx")

# remove duplicated genes
kidney_macrophage <- kidney_macrophage %>% 
  rowwise() %>% 
  mutate(m = mean(c(blood_mac_1, blood_mac_2, blood_mac_3, sm_mac_1, sm_mac_2, sm_mac_3))) %>% 
  arrange(-m) %>% 
  dplyr::select(-m)
kidney_macrophage <- kidney_macrophage[!duplicated(kidney_macrophage$geneID), ]
```

```{r}
kidney_macrophage <- kidney_macrophage %>% 
  dplyr::mutate(rank = -sign(logCPM) * (- log10(PValue))) %>% 
  arrange(-rank) 
ranked <- kidney_macrophage$rank
names(ranked) <- kidney_macrophage$geneID
ranked %>% head
```


```{r}
# msigdbr_collections() %>% pull(gs_cat) %>% table
# only use terms has experiment and phylogenetic evidence 
go_evidence_code <- c("EXP", "IDA", "IPI", "IMP", "IGI", "IEP", 
                      "HTP", "HDA", "HMP", "HGI", "HEP", 
                      "IBA", "IBD", "IKR", "IRD") # phylogeny evidence

key_df <- select(org.Mm.eg.db, 
                 keys = keys(org.Mm.eg.db), 
                 keytype = "ENTREZID", 
                 columns = c("SYMBOL", "GO"))

key_df <- key_df %>% 
  filter(EVIDENCE %in% go_evidence_code)
go_list <- split(key_df$SYMBOL, key_df$GO)

# C5 <- msigdbr(species = "mouse", category = "C5") 

go_res <- fgseaMultilevel(pathways = go_list, 
                         stats = ranked, 
                         minSize = 10,
                         maxSize = 2000,
                         eps = 0)

go_df <- select(GO.db, 
                keys = key_df$GO, 
                keytype = "GOID", 
                columns = c("GOID", "TERM", "ONTOLOGY"))

go_ana_res <- left_join(go_res, go_df, by = c('pathway' = "GOID")) %>% 
  distinct(pathway, .keep_all = T) %>%
  relocate(pathway, term = TERM, ontology = ONTOLOGY)

go_ana_res %>% 
  filter(ontology == "BP") %>%
  arrange(-NES)
```

```{r}
go_ana_res %>% 
  filter(ontology == "MF") %>% 
  arrange(NES)
```



```{r}
leadingeage_2 <- H_res %>% 
  arrange(-NES) %>% 
  filter(grepl("^GOCC", pathway, ignore.case = F)) %>% 
  head(2) %>% 
  pull(leadingEdge) 

intersect(leadingeage_2[[1]], leadingeage_2[[2]]) %>% sort()
```



```{r}
gs <- c()
for(i in seq_along(H_res$leadingEdge)){
    gs = append(gs, H_res$leadingEdge[[i]])
}
gs  <- gs %>% unique() %>% sort()
gs %>% head

m <- matrix(0, nrow = length(H_res$pathway), 
            ncol = length(gs))
colnames(m) <- gs
rownames(m) <- H_res$pathway

for(i in seq_len(dim(H_res)[1])){
  m[i, H_res$leadingEdge[[i]]] = 1
}
m[, 1:10]
```

```{r}
library(cluster)

dis_H_res_leading <- daisy(x = m, metric = "gower", type = list(asymm = seq(1:dim(m)[2])))

tiff("H_res_leadingedge_similarity.tiff", width = 900, height = 900)
pheatmap::pheatmap(1 - as.matrix(dis_H_res_leading), 
                   fontsize = 8, 
                   clustering_method = "ward.D2", 
                   angle_col = 315, 
                   cutree_rows = 4, 
                   cutree_cols = 4)
dev.off()
```

```{r}
inter <- m[c("oxidative_phosphorylation", "fatty_acid_metabolism", "adipogenesis"), ] %>% t() %>% 
  apply(1, sum) %>% .[which(. == 3)] %>% names()

AnnotationDbi::select(org.Mm.eg.db, 
                      keys = inter, 
                      keytype = "SYMBOL", 
                      columns = c("SYMBOL", "GENENAME"))
```



```{r}
c5 <- msigdbr(species = "mouse", category = "C5")
c5_res <- fgseaMultilevel(pathways = split(c5$gene_symbol, c5$gs_name), 
                          stats = ranked, 
                          minSize = 15, 
                          eps = 0)
c5_res_filtered <- c5_res %>% arrange(NES) %>% 
  filter(padj < 0.01, NES < 0) %>%
  mutate(pathway = tolower(pathway))
```

```{r}
gs <- c()
for(i in seq_along(c5_res_filtered$leadingEdge)){
    gs = append(gs, c5_res_filtered$leadingEdge[[i]])
}

gs <- gs %>% unique() %>% sort()
gs %>% head

m <- matrix(0, nrow = dim(c5_res_filtered)[1], 
            ncol = length(gs))
colnames(m) <- gs
rownames(m) <- c5_res_filtered$pathway

for(i in seq_len(dim(c5_res_filtered)[1])){
  m[i, c5_res_filtered$leadingEdge[[i]]] = 1
}
```

```{r}
c5_res_dis <- daisy(x = m, 
                    metric = "gower", 
                    type = list(asymm = seq(1, dim(m)[2])))

pdf("go.pdf")
pheatmap::pheatmap(1 - as.matrix(c5_res_dis), 
                   fontsize = 3, 
                   angle_col = 315, 
                   cutree_cols = 4, 
                   cutree_rows = 4)
dev.off()
```


