---
title: "代谢重编程与胰腺癌转移"
format: docx
number-sections: true
number-depth: 3
link-citations: true
csl: /home/yincy/styles/american-journal-of-medical-genetics.csl
bibliography: PDAC.bib
editor: source
---

# 背景

胰腺癌属于消化系统肿瘤，虽然其发病率不高但是死亡率却是所有肿瘤中最高的，5年生存率不足5%[@Cohen2015]。究其原因主要是胰腺癌早期症状不明显，当前的早期筛查费用比较贵，在确诊时绝大多数患者都已处于晚期[@Vareedayah2018-xv]。上个世纪20年代Otto Warburg发现在分裂旺盛的肿瘤组织中细胞摄取葡萄糖的速率增加，但是代谢上却主要使用糖酵解而非氧化磷酸化为细胞提供能量，这一现象称为瓦格博效应。在PDAC患者中发现90%的患者都带有KRAS突变，而研究发现KRAS突变能够促进PDAC代谢重编程、促进PDAC葡萄糖转运体和六磷酸葡萄糖激酶的表达，进而促进糖酵解过程[@Cohen2015]。类似地研究也发现TP53突变也能够促进PDAC代谢重编程。但是这些突变信息不是很容易得获得，因此并不能作为早期筛查PDAC的标志物。

# 数据

## 胰腺癌测序数据

| Dataset ID  | 样本类型 | 样本数 | 样本特征                                       | 数据类型    |
|:------------|:---------|:-------|:-----------------------------------------------|:------------|
| *GSE253260* | 组织     | 397    | 106个转移样本和291个胰腺癌样本                 | bulk RNAseq |
| GSE77858    | 组织     | 85     | 77个胰腺癌样本，3个正常胰腺样本，5个胰腺炎样本 | microarray  |
| *GSE263733* | 组织     | 218    | 175胰腺癌样本和43个肝转移样本                  | single cell |
| GSE79668    | 组织     | 51     | 胰腺癌组织                                     | bulk RNAseq |
| *TCGA-PAAD* | 组织     | 178    | 胰腺癌组织                                     | bulk RNAseq |

# 分析流程

**Figure1：** 实验流程图。

**Figure2：** 合并GSE253260数据集中原位和转移样本的单细胞数据。绘制出降维后的tSNE图。把肿瘤细胞提取出来重新降维聚类，把不同cluster按照原位肿瘤和转移肿瘤的占比分为原位肿瘤群、转移肿瘤群和混合群。比较转移肿瘤群和原位肿瘤群并进行功能富集分析。取显著富集到的代谢相关的基因集与GSE263733表达基因的交集，称为META_ACTIVE基因集。对METAD_ACTIVATE基因集进行GSEA分析。使用META_ACTIVE基因集计算所有肿瘤细胞的AUCell Score，选择一个临界值把所有的肿瘤细胞分META-active 和META-silent两群。使用CIBERSORTx对TCGA-PAAD bulk RNAseq的数据进行代谢活性分析，GSE263733做为参考数据集，划分出来META_active、META_silent和Non_malignant细胞在不同样本中的占比。把TCGA-PAAD样本按照META_active、META_silent和Non_malignant细胞占比划分为METArisk_high和METArisk_low组。对METArisk_high和METArisk_low组进行生存分析。

**Figure3：** 取META_ACITATE细胞的signature gene和META_ACTIVE基因的交集称为MRGs。取MRGs、META_ACTIVATE和METArisk_high和METArisk_low组差异基因的交集，得到备选基因集。对备选基因集进行SVM-RFE和多变量Cox分析，筛选与生存相关的基因。并对这些筛选到的基因进行生存分析（按照表达水平分为高低组）。画出TCAG-PAAD METArisk_high和METArisk_low组中筛选到的基因的表达水平的箱线图。依据生存分析和METArisk_high和METArisk_low表达水平筛选出一个或者多个表达水平与胰腺癌病情成正相关的基因。使用IHC和RT-PCR验证肿瘤组织和癌旁组织中该基因表达水平的差异。

**Figure4：** 在胰腺癌细胞系HPAC和LTPA中敲降上一步筛选到的靶基因。首先用RT-PCR和western blot分别在RNA和蛋白水平验证敲降的效率。敲降靶基因后与对照比较分别验证细胞的分裂能力、迁移能力、细胞的凋亡水平以及基因组突变水平。

**Figure5：** 使用Oncopredict R包计算胰腺癌化疗药物Gemcitabine对MATEeisk_high和METArisk_low组患者的抑制中位数（IC50）。按照靶基因的表达水平把TCGA-PAAD样本分为靶基因高表达和靶基因低表达组，画出Gemcitabine对靶基因高表达组和低表达组的IC50。使用CARE数据库分析靶基因的表达水平与耐药性之间的关系。

按照是否敲降靶基因、有无化疗处理将裸鼠划分为4组，分别为对照组：将没有敲降靶基因的胰腺癌细胞系接种到裸鼠皮下；靶基因敲降组：将靶基因敲降的胰腺癌细胞系接种到裸鼠皮下；化疗组：皮下接种没有敲降靶基因的胰腺癌细胞系并进行化疗处理；靶基因敲降＋化疗处理组：将敲降靶基因的胰腺癌细胞系接种到裸鼠皮下并进行化疗处理。从接种肿瘤开始，选取不同的时间点测量肿瘤的大小，实验结束后将肿瘤取下测量大小并拍照记录，同时取下肝脏使用组化研究胰腺癌肝转移在不同组之间的差别。

**Figure6：** 使用Oncopredict计算的IC50研究TP53表达水平与胰腺癌耐药性之间的关系。TP53表达水平与靶基因表达水平之间的散点图，找靶基因与TP53在表达水平上的关系。 敲降靶基因观察TP53及其效应蛋白P21在RNA水平和蛋白水平的变化。敲降靶基因后使用流式分析不同周期细胞的占比，观察敲降靶基因后对细胞分裂的影响。

**Figure7：** 对靶基因高表达和靶基因低表达组进行基因集变异分析(GSVA)。找出与靶基因功能直接相关的基因集，对富集到的基因集进行相关性分析，找到一个与靶基因功能集相关的基因集。分析靶基因与相关基因集中基因表达水平之间的关系。使用相关基因集中的基因对TCGA-PAAD样本进行一致性聚类，对不同的亚群进行生存分析。敲降胰腺癌细胞系的靶基因后使用PAS和2—NBDG检测细胞内糖原和多糖的含量，以此确定敲除靶基因对糖原代谢的影响。敲除靶基因后检测细胞内谷胱氨肽的含量，以此确定糖原代谢与谷胱甘肽合成代谢存在关联。谷胱甘肽是细胞内重要的还原剂，用于降低细胞内活性氧水平。敲除靶基因后检测细胞内活性氧（ROS）的水平用于确认细胞内谷胱甘肽的水平发生改变。

**Figure8：** 靶基因调控胰腺癌转移以及耐药的机制示意图。

```{r, echo=FALSE, eval=FALSE}
library(rentrez)

term = "(Pancreatic Adenocarcinoma[title]) AND (Homo sapiens[orgn]) AND (10:49[nsam])"
res <- entrez_search(db = "gds", term = term, retmax = 1000)
res$ids
```

{{<pagebreak>}}

# 参考文献 {.unnumbered}

::: {#refs}
:::
