---
title: "oligo"
author: "YinCY"
format: html
editor: source
---


# Introduction
Oligo is a Bioconductor package for preprocessing oligonucleotide microarrays. It currently supports
chips produced by Affymetrix and NimbleGen and uses files provided by these manufacturers in their
native format. The package provides a unified framework for preprocessing and uses the data representation established by the Bioconductor project, which simplifies the interface with other packages in
the project.

The oligo package allows users to preprocess their microarray data using R. This is a convenient
approach as analysts can combine the preprocessed data with a number of tools already implemented
in R, like downstream analyses and visualization.

The software is designed to support large datasets and also provides parallel execution of common tasks
like background subtraction, normalization and summarization.

oligo can appropriately handle data files for Affymetrix and NimbleGen designs. The supported formats are CEL (Affymetrix) and XYS (NimbleGen).  


```{r}
library(oligo)
files <- list.celfiles("/home/yincy/git/data/zhuyi/dermatomyositis/E-MTAB-2967/", 
                       full.names = TRUE)
files
mtx <- read.celfiles(files)
mtx %>% class
mtx %>% dim
mtx
```































