---
title: "坏死性调亡与肾癌"
format: docx
bibliography: RCC.bib
csl: /home/yincy/styles/american-journal-of-medical-genetics.csl
link-citations: true
number-sections: true
number-depth: 3
editor: source
---

# 背景

坏死性凋亡是一种受到严格调控的细胞坏死，其通常在凋亡（apoptosis）触发条件不足的情况下发生[@DArcy2019]。目前研究较为清楚的是激活TNFR1受体所介导的坏死性凋亡，但是研究显示其他受体如TNFR2同样也可以介导坏死性凋亡的发生。在肾癌的研究中发现TNFR2的表达水平与患者的的病情等级呈正相关，血浆中TNFR2的水平也与肾脏肿瘤的转移和病情等级呈正相关[@AlLamki2010; @Einollahi2012]。体外实验研究发现使用TNF刺激TNFR2能够促进肾脏肿瘤进入分裂期[@Wang2013]。肾脏肿瘤由多种亚型构成，其中最常见的是肾透明细胞癌（ccRCC）约占所有肾脏肿瘤的80%以上。研究发现坏死性凋亡也参与到肾癌的发生与发展过程[@Fu2022-md; @Bao2022-rz]，但是具体有哪些坏死性相关基因参与到肾癌的发生发展过程以及其具体的机制目前了解的还较为有限。本研究旨在通过机器学习等方法筛选与肾癌发展相关的坏死性凋亡基因。

# 数据

## 坏死性调亡相关基因

通过necroptotic和necroptosis关键词在Gene Ontology，KEGG pathway和reactome pathway中检索坏死性凋亡相关基因集合，并取并集。

## 肾癌相关的测序数据

| Dataset ID  | 样本类型 | 样本数 | 样本特征                                  | 数据类型    |
|:------------|:---------|:-------|:------------------------------------------|:------------|
| GSE29609    | 组织     | 39     | 肾癌组织(ccRCC)                           | microarray  |
| GSE162948   | 组织     | 32     | 肾癌组织(ccRCC)                           | bulk RNAseq |
| GSE14762    | 组织     | 22     | 12个正常肾脏组织，10个肾癌组织(ccRCC)     | microarray  |
| *GSE7367*   | 组织     | 48     | 24个癌旁组织和24和对应的肾癌组织(ccRCC)   | microarray  |
| *GSE102101* | 组织     | 20     | 10个癌旁组织和10和对应的肾癌组织(ccRCC)   | bulk RNAseq |
| *GSE73731*  | 组织     | 265    | 肾癌组织(ccRCC)                           | microarray  |
| *GSE40435*  | 组织     | 202    | 101个癌旁组织和101和对应的肾癌组织(ccRCC) | microarray  |
| *TCGA-KIRC* | 组织     | 534    | 肾癌组织(ccRCC，有生存时间和状态信息)     | bulk RNAseq |

# 分析流程

**Figure1：** 分析流程图和样本基线表。

**Figure2：** GSE7367, GSE102101和GSE40435数据合并去批次并进行差异分析。差异基因与坏死性凋亡相关基因取交集。绘制坏死性凋亡相关基因在染色体上的位置，以及坏死性凋亡相关基因的拷贝数变异频率。查看交集基因在TCGA-KIRC中的单核苷酸突变情况，绘制交集基因的PPI网络图。

**Figure3：** 使用基因表达水平、生存分析和Cox分析获得与生存显著相关的坏死性调亡基因。使用筛选到的基因对TCGA-KIRC进行一致性聚类分析。对TCGA-KIRC不同亚群进行差异基因分析、生存分析和聚类分析。绘制TCGA-KIRC的聚类图（PCA）,差异基因的热图，同时加上多种临床信息如性别、年龄、肿瘤病情分级等信息。对不同亚群的TCGA-KIRC进行基因集变异分析（GSVA）和免疫浸润分析（ssGSEA）。

**Figure4：** 使用TCGA-KIRC不同亚群间的差异基因进行功能富集分析，并绘制富集分析的气泡图。使用TCGA-KIRC不同亚群的差异基因对TCGA-KIRC重新进行一致性聚类分析，并对新得到的亚群进行生存分析。

**Figure5：** 把TCGA-KIRC随机等分成训练组和测试组，使用训练组进行Cox分析，筛选与生存相关的基因，并计算每个样本的风险值，依据风险值把样本分为高风险组和低风险组。同理计算出测试组、TCGA-KIRC和验证数据GSE73731中每个样本的风险值，并依据风险值将其分为低风险组和高风险组。并对训练集、测试集、TCGA-KIRC和验证数据GSE73731的高风险和低风险组进行生存分析。

**Figure6：** 使用生存时间及状态信息与临床信息进行但因素和多因素Cox分析，并绘制相应的风险比率图、列线图和ROC曲线。

**Figure7：** 使用坏死凋亡相关基因对TCGA-KIRC进行一致性聚类，绘制不同亚群风险值的箱线图。比较TCGA-KIRC高风险组和低风险组中坏死相关基因的表达水平。使用桑吉图（sankey graph）绘制出TCGA-KIRC不同样本在各个分类指标中的分布情况。

**Figure8：** 计算筛选到的坏死性凋亡相关基因的表达水平与免疫细胞浸润水平之间的相关系数及其显著水平，并绘制热图。绘制TCGA-KIRC各个样本风险值与不同免疫细胞浸润水平之间的散点图。绘制TCGA-KIRC高风险组与低风险组之间的单核苷酸突变图。计算高风险组与低风险组的突变负荷（tumor mutation burden），并绘制箱线图以及样本的突变负荷与风险值之间的散点图。

**Figure9：** 分析TCGA-KIRC高风险组与低风险组对不同化疗药的敏感性，并绘制箱线图。


# 附表

1.  肿瘤坏死相关基因列表。
2.  使用基因表达水平、生存分析和Cox分析得到的基因列表。
3.  GO富集分析结果。
4.  KEGG富集分析结果。
5.  基因集变异分析结果。
6.  免疫浸润分析结果。
7.  Cox生存分析得到的系数不为零的基因及其相关系数。
8.  药物敏感性分析结果。


```{r, echo=FALSE, eval=FALSE}
library(rentrez)

?entrez_search

# kidney cancer
# renal cancer
# renal carcinoma
# kidney carcinoma
# ccRCC

term = "(kidney carcinoma[title] AND (Homo sapiens[orgn]) AND (50:99[nsam]))"
res <- entrez_search(db = "gds", term = term, retmax = 100)
res$ids
```


**该设计方案参考文章[@Zhang2022]，IF=4.7。**

{{< pagebreak >}}

# 参考文献 {.unnumbered}

::: {#refs}
:::
