---
title: "BED"
author: "YinCY"
format: html
editor: source
---

The BED format consists of one line per feature, each containing 3-12 columns of data, plus optional track definition lines.

## Required fields
The first three fields in each feature line are required:

1. `chrom`: name of the chromosome or scaffold. Any valid seq_region_name can be used, and chromosome names can be given with or without the 'chr' prefix.

2. `chromStart`: Start position of the feature in standard chromosomal coordinates.

3. `chromEnd`: End position of the feature in standard chromosome coordinates.


## Optional fields
Nine additional fields are optional. 

4. `name`: Label to be displayed under the feature, if turned on in "Configure this page".  

5. `score`: A score between 0 and 100. 

6. `strand`: defined as + (forward) or - (reverse).

7. `thickStart`: coordinate at which to start drawing the feature as a solid rectangle.  

8. `thickEnd`: coordinate at which to stop drawing the feature as a solid rectangle.  

9. `itemRgb`: an RGB colour value. Only used if there is a track line with the value of itemRgb set to 'on'. 

10. `blockCount`: the number of sub-elements within the feature.  

11. `blockSize`: the size of these sub-elements.  

12. `blockStart`: the start coordinate of each sub-element.  







