---
title: "TCGAretriever"
author: "YinCY"
format: html
editor: visual
---

```{r}
#| message: false
#| warning: false

library(TCGAretriever)
library(magrittr)
library(stringr)
library(stringr.plus)
library(EnsDb.Hsapiens.v86)
```

# call cancer types
```{r}
all_cancer_types <- get_cancer_types()
all_cancer_types
all_cancer_types[grep("colon", all_cancer_types$name, ignore.case = T, value = F), ]
```

# all cancer studies
```{r}
all_studies <- get_cancer_studies()
all_studies %>% dplyr::filter(grepl("colon", name, ignore.case = T))
```

# gene identifiers
```{r}
all_gene_identifiers <- data.frame(ensembl = keys(EnsDb.Hsapiens.v86), 
                                   symbol = mapIds(EnsDb.Hsapiens.v86, keys = keys(EnsDb.Hsapiens.v86), keytype = "GENEID", column = "SYMBOL"))
all_gene_identifiers
```

```{r}
# what types of studies this study conducted
get_genetic_profiles(csid = "coad_silu_2022")
```

```{r}
cases <- get_case_lists(csid = "coad_silu_2022")

gene_list <- split(all_gene_identifiers$symbol, 
                   f = cut(seq_along(all_gene_identifiers$symbol), ceiling(nrow(all_gene_identifiers)/500)))

gene_list %>% length
names(gene_list) <- NULL
gene_list %>% sapply(length) %>% table

molecular_list <- list()

for(i in seq_along(gene_list)){
    x <- get_molecular_data(case_list_id = "coad_silu_2022_all", 
                             gprofile_id = "coad_silu_2022_rna_seq_mrna", 
                             glist = gene_list[[i]])
    
    molecular_list[[i]] <- x
}

df <- purrr::map_df(molecular_list, dplyr::bind_rows)
df %>% class
df %>% head
```

```{r}
clinical_data_coad <- get_clinical_data(csid = "coad_silu_2022", case_list_id = "coad_silu_2022_all")
```

```{r}
df <- df %>% tidyr::pivot_longer(cols = -c(1:3), names_to = "sampleId", values_to = "value")
df <- dplyr::left_join(df, clinical_data_coad, by = "sampleId")
df %>% colnames()
df$SAMPLE_TYPE %>% table
```





























