---
title: "GEOmetadb"
author: "yincy"
date: "3/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,message=FALSE, warning=FALSE}
library(GEOmetadb)
library(DBI)
library(RSQLite)
library(tidyverse)
```


```{r}
con <- dbConnect(drv = RSQLite::SQLite(), "f:/git/Data/GEOmetadb.sqlite")
```

```{r}
dbListFields(con, "gsm")
```

```{r}
sample_sources <- dbReadTable(con, 'gsm') %>% 
    group_by(organism_ch1, source_name_ch1) %>% 
    summarise(n = n())

sample_sources <- sample_sources %>% arrange(-n)



sample_sources %>% 
    fct_collapse(
        .f = source_name_ch1, 
        pbmc = grep("blood|pbmc|plasma", sample_sources %>% pull(source_name_ch1), value = T), 
        brain = grep("cortex|brain|hippocampus|striatum|hypothalamus", sample_sources %>% pull(source_name_ch1), value = T), 
        tumor = grep("tumor|cancer", sample_sources %>% pull(source_name_ch1), value = T), 
        ipsc = grep("ipsc", sample_sources %>% pull(source_name_ch1), value = T),
        spleen = grep("spleen", sample_sources %>% pull(source_name_ch1), value = T), 
        psoriasis = grep("psoriasis", sample_sources %>% pull(source_name_ch1), value = T), 
        retina = grep("retina|eye", sample_sources %>% pull(source_name_ch1), value = T), 
        `bone marrow` = grep("bone marrow", sample_sources %>% pull(source_name_ch1), value = T), 
        `T cell` = grep("T cell", sample_sources %>% pull(source_name_ch1), value = T), 
        embryonic = grep("embryonic", sample_sources %>% pull(source_name_ch1), value = T), 
        liver = grep("liver", sample_sources %>% pull(source_name_ch1), value = T), 
        lung = grep("lung", sample_sources %>% pull(source_name_ch1), value = T), 
        breast = grep("breast", sample_sources %>% pull(source_name_ch1), value = T), 
        kidney = grep("kidney", sample_sources %>% pull(source_name_ch1), value = T), 
        leukemia = grep("leukemia", sample_sources %>% pull(source_name_ch1), value = T))
```

```{r}
tissue_organ <- c("spleen", "brain", "liver", "serum", "blood", 
                  "cortex", "PBMC", "Psoriasis", "melanoma", "Bone marrow", 
                  "Hippocampus", "Hippocampus", "striatum", "retina", "lymphoblast", 
                  "astrocytoma", "Head and neck cancer single cell", "colon", "dendritic cell", "thymus", 
                  "embryonic", "fetal", "prostate", "testis", "skin", 
                  "vascular", "lymph node", "muscle", "breast", "renal")
```


```{r}
gsm_table <- dbReadTable(con, "gsm") %>% 
  filter(grepl(str_c(tissue_organ, collapse = "|"), source_name_ch1, ignore.case = T)) %>% 
  type_convert()

gsm_table %>% 
  filter(submission_date >= '2010-01-01', grepl("illumina", label_protocol_ch1, ignore.case = T))
```

```{r}
hsa_retina_ngs <- dbGetQuery(conn = con, 
           statement = "select gse.gse, gsm.title, gse.summary, 
           gse.pubmed_id, gpl.gpl, gpl.technology, gsm.gsm, 
           gsm.source_name_ch1, gsm.organism_ch1, gsm.molecule_ch1
           from gsm 
           join gse_gsm on gsm.gsm=gse_gsm.gsm 
           join gse on gse_gsm.gse=gse.gse 
           join gse_gpl on gse_gpl.gse=gse.gse 
           join gpl on gse_gpl.gpl=gpl.gpl 
           where gsm.organism_ch1 = 'Homo sapiens' 
           and gpl.technology='high-throughput sequencing'")
```


```{r}
hsa_retina_ngs %>% 
    filter((grepl("", title) | grepl("retina", summary) | grepl("retina", source_name_ch1)) & technology == "high-throughput sequencing")
```


```{r}
hsa_retina_ngs %>% 
    filter((grepl("pbmc|`whole blood`", title) | grepl("pbmc|`whole blood`", summary) | grepl("pbmc|`whole blood`", source_name_ch1)) & technology == "high-throughput sequencing") %>% 
    pull(summary) %>% 
    unique()
```


```{r}
pat <- c("AMD", "RPE")
hsa_retina_amd <- hsa_retina_ngs %>% 
  filter(grepl(stringr::str_c(pat, collapse = "|"), summary, ignore.case = F))

hsa_retina_amd %>% 
  dplyr::filter(grepl("AMD", summary, ignore.case = F))
```







