---
title: "crisprDesign"
author: "YinCY"
format: html
---

# Introduction
`crisprDesign` is the core package of the `crisprVerse` ecosystem, and plays the role of a one-step shop for designing and annotating CRISPR guide RNA (gRNA) sequences. This includes the characterization of no-targets and off-targets using different aligners, no- and off-target scoring, gene context annotation, SNP annotation, sequence feature characterization, repeat annotation, and many more.  

The currently support five types of CRISPR modalities (modes of perturbation): CRISPR knockout (CRISPRko), CRISPR activation (CRISPRa), CRISPR interference (CRISPRi), CRISPR base editing (CRISPRbe), and CRISPR knockdown (CRISPRkd).

It utilizes the `crisprBase` packae to enable gRNA design for any CRISPR nuclease and base editor via the `XrisprNuclease` and `BaseEditor` classes, respectively. Nucleases that are commonly used in the field are provided, including DNA-targeted nucleases and RNA-targeted nucleases (CasRx(RfxCas13d)).

Finally, more specialized gRNA design functionalities are also available, including design for optical pooled screening (OPS), paired gRNA design, and gRNA filtering and ranking functionalities.





























