---
title: "01_Introduction"
author: "yincy"
date: "2023-03-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Introduction
Single-cell transcriptome sequencing (sc-RNA-seq) experiments allow us to discover new cell types and help us understand how they arise in development. The Monocle 3 package provides a toolkit for analyzing single-cell gene expression experiments.

Monocle3 can help you perform three main types of analysis:

- **Clustering, classifying, and counting cells**. Single-cell RNA-Seq experiments allow you to discover new (and possibly rare) subtypes of cells. Monocle 3 helps you identify them.

- **Constructing single-cell trajectories**. In development, disease, and throughout life, cells transition from one state to another. Monocle 3 helps you discover these transitions.

- **Differential expression analysis**. Characterizing new cell types and states begins with comparisons to other, better understood cells. Monocle 3 includes a sophisticated, but easy-to-use system for differential expression.






